# Install Palmart Till Print Bridge once on Windows.
# ASCII-only so Windows PowerShell 5.1 parses this file reliably.
# Copies into %LOCALAPPDATA%, starts hidden, auto-starts at every logon.
$ErrorActionPreference = "Stop"

$PkgDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$InstallDir = Join-Path $env:LOCALAPPDATA "Palmart\till-print-bridge"
$BridgeSrc = Join-Path $PkgDir "till-print-bridge.mjs"
$BridgeDst = Join-Path $InstallDir "till-print-bridge.mjs"
$VbsPath = Join-Path $InstallDir "run-hidden.vbs"
$LogPath = Join-Path $InstallDir "bridge.log"
$StartCmdPath = Join-Path $InstallDir "start-till-print-bridge.cmd"
$UninstallPath = Join-Path $InstallDir "Uninstall-Palmart-Print-Bridge.ps1"
$TaskName = "PalmartTillPrintBridge"
$StartupName = "Palmart-Till-Print-Bridge.vbs"
$HealthUrl = "http://127.0.0.1:19500/health"
$Port = 19500

function Write-Step([string]$Message) {
  Write-Host (" - " + $Message)
}

function Find-NodeExe {
  $cmd = Get-Command node -ErrorAction SilentlyContinue
  if ($cmd -and $cmd.Source -and (Test-Path $cmd.Source)) {
    return $cmd.Source
  }
  $pf86 = [Environment]::GetEnvironmentVariable("ProgramFiles(x86)")
  $candidates = @(
    (Join-Path $env:ProgramFiles "nodejs\node.exe"),
    (Join-Path $env:LOCALAPPDATA "Programs\node\node.exe")
  )
  if ($pf86) {
    $candidates += (Join-Path $pf86 "nodejs\node.exe")
  }
  foreach ($c in $candidates) {
    if ($c -and (Test-Path $c)) { return $c }
  }
  return $null
}

function Test-BridgeHealth {
  try {
    return Invoke-RestMethod -Uri $HealthUrl -TimeoutSec 2
  } catch {
    return $null
  }
}

function Stop-BridgeOnPort {
  try {
    $conns = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue
    foreach ($c in $conns) {
      if ($c.OwningProcess -and $c.OwningProcess -gt 0) {
        Stop-Process -Id $c.OwningProcess -Force -ErrorAction SilentlyContinue
      }
    }
  } catch {
    # Older Windows without Get-NetTCPConnection - ignore.
  }
}

function Wait-BridgeHealth([int]$Attempts = 15) {
  for ($i = 0; $i -lt $Attempts; $i++) {
    $health = Test-BridgeHealth
    if ($health -and $health.ok) { return $health }
    Start-Sleep -Milliseconds 700
  }
  return $null
}

function Write-HiddenVbs([string]$NodeExe, [string]$BridgeFile, [string]$WorkDir, [string]$OutVbs, [string]$OutLog) {
  # Use Chr(34) for quotes - nested """ quoting is fragile in VBScript.
  $nodeLit = $NodeExe.Replace('"', '')
  $bridgeLit = $BridgeFile.Replace('"', '')
  $workLit = $WorkDir.Replace('"', '')
  $logLit = $OutLog.Replace('"', '')
  $lines = @(
    "' Auto-generated by Palmart Print Bridge installer - do not edit.",
    'Set sh = CreateObject("WScript.Shell")',
    ('sh.CurrentDirectory = "' + $workLit + '"'),
    ('sh.Environment("Process")("TILL_PRINT_BRIDGE_LOG") = "' + $logLit + '"'),
    ('nodeExe = "' + $nodeLit + '"'),
    ('bridge = "' + $bridgeLit + '"'),
    'cmd = Chr(34) & nodeExe & Chr(34) & " " & Chr(34) & bridge & Chr(34)',
    "' 0 = hidden window, False = do not wait",
    "sh.Run cmd, 0, False"
  )
  [System.IO.File]::WriteAllLines($OutVbs, $lines, [System.Text.Encoding]::ASCII)
}

function Install-StartupEntry([string]$SourceVbs) {
  $startupDir = [Environment]::GetFolderPath("Startup")
  if (-not $startupDir) { return $null }
  New-Item -ItemType Directory -Force -Path $startupDir | Out-Null
  $dest = Join-Path $startupDir $StartupName
  Copy-Item -Force $SourceVbs $dest
  return $dest
}

function Install-LogonTask([string]$WscriptExe, [string]$VbsFile, [string]$WorkDir) {
  $principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited
  $action = New-ScheduledTaskAction -Execute $WscriptExe -Argument ('"' + $VbsFile + '"') -WorkingDirectory $WorkDir
  $trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME

  # ExecutionTimeLimit Zero = run forever (default ~72h would kill the bridge).
  try {
    $settings = New-ScheduledTaskSettingsSet `
      -AllowStartIfOnBatteries `
      -DontStopIfGoingOnBatteries `
      -DontStopOnIdleEnd `
      -StartWhenAvailable `
      -ExecutionTimeLimit ([TimeSpan]::Zero) `
      -RestartCount 10 `
      -RestartInterval (New-TimeSpan -Minutes 1) `
      -MultipleInstances IgnoreNew
  } catch {
    $settings = New-ScheduledTaskSettingsSet `
      -AllowStartIfOnBatteries `
      -DontStopIfGoingOnBatteries `
      -StartWhenAvailable `
      -ExecutionTimeLimit ([TimeSpan]::Zero)
  }

  Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
  Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Principal $principal `
    -Description "Palmart Till Print Bridge (127.0.0.1:19500) - background, no window" `
    -Force | Out-Null

  try {
    Start-ScheduledTask -TaskName $TaskName -ErrorAction Stop
  } catch {
    # Task may refuse Start if already running; VBS start below covers it.
  }
}

# Preconditions
$Node = Find-NodeExe
if (-not $Node) {
  throw "Node.js not found. Install the LTS build from https://nodejs.org/ then run this installer again."
}
if (-not (Test-Path $BridgeSrc)) {
  throw "Missing till-print-bridge.mjs next to this installer."
}

$Wscript = Join-Path $env:SystemRoot "System32\wscript.exe"
if (-not (Test-Path $Wscript)) {
  $Wscript = "wscript.exe"
}

Write-Host ""
Write-Host "=== Palmart Till Print Bridge - Windows install ==="
Write-Step ("Node: " + $Node)
Write-Step ("Install dir: " + $InstallDir)

# Copy files
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
Copy-Item -Force $BridgeSrc $BridgeDst
Write-HiddenVbs -NodeExe $Node -BridgeFile $BridgeDst -WorkDir $InstallDir -OutVbs $VbsPath -OutLog $LogPath

$startCmdLines = @(
  "@echo off",
  "REM Ensures the background bridge is running (no keep-open window).",
  'cd /d "%~dp0"',
  "powershell -NoProfile -ExecutionPolicy Bypass -Command ^",
  '  "try { $h = Invoke-RestMethod -Uri http://127.0.0.1:19500/health -TimeoutSec 2; if ($h.ok) { Write-Host ''Till Print Bridge already running.''; exit 0 } } catch {}"',
  'start "" /B wscript.exe "%~dp0run-hidden.vbs"',
  "timeout /t 2 /nobreak >nul",
  "powershell -NoProfile -ExecutionPolicy Bypass -Command ^",
  '  "try { $h = Invoke-RestMethod -Uri http://127.0.0.1:19500/health -TimeoutSec 3; if ($h.ok) { Write-Host ''Till Print Bridge started in the background.''; exit 0 } else { exit 1 } } catch { Write-Host ''Bridge did not become healthy. See bridge.log''; exit 1 }"',
  "if errorlevel 1 (",
  "  echo See %LOCALAPPDATA%\Palmart\till-print-bridge\bridge.log",
  "  pause",
  "  exit /b 1",
  ")",
  "timeout /t 2 /nobreak >nul"
)
[System.IO.File]::WriteAllLines($StartCmdPath, $startCmdLines, [System.Text.Encoding]::ASCII)

$uninstallLines = @(
  '$ErrorActionPreference = "SilentlyContinue"',
  '$InstallDir = Split-Path -Parent $MyInvocation.MyCommand.Path',
  '$TaskName = "PalmartTillPrintBridge"',
  '$Startup = Join-Path ([Environment]::GetFolderPath("Startup")) "Palmart-Till-Print-Bridge.vbs"',
  'Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false',
  'Remove-Item -Force $Startup',
  'Get-NetTCPConnection -LocalPort 19500 -State Listen -ErrorAction SilentlyContinue | ForEach-Object { Stop-Process -Id $_.OwningProcess -Force -ErrorAction SilentlyContinue }',
  'Write-Host "Stopped autostart. Remove folder to fully uninstall:" $InstallDir'
)
[System.IO.File]::WriteAllLines($UninstallPath, $uninstallLines, [System.Text.Encoding]::ASCII)

# Autostart: Startup folder (most reliable for till users)
$startupPath = $null
try {
  $startupPath = Install-StartupEntry -SourceVbs $VbsPath
  if ($startupPath) { Write-Step ("Startup folder: " + $startupPath) }
} catch {
  Write-Warning ("Could not add Startup folder entry: " + $_.Exception.Message)
}

# Autostart: Scheduled Task (restart-on-crash, unlimited runtime)
$taskOk = $false
try {
  Install-LogonTask -WscriptExe $Wscript -VbsFile $VbsPath -WorkDir $InstallDir
  $taskOk = $true
  Write-Step ("Scheduled task: " + $TaskName + " (logon, hidden, unlimited)")
} catch {
  Write-Warning ("Scheduled task not registered (Startup folder still used): " + $_.Exception.Message)
}

# Start now (hidden)
$already = Test-BridgeHealth
if ($already -and $already.ok) {
  Write-Step ("Bridge already healthy on port " + $Port)
} else {
  Stop-BridgeOnPort
  Start-Sleep -Milliseconds 400
  Start-Process -FilePath $Wscript -ArgumentList ('"' + $VbsPath + '"') -WindowStyle Hidden | Out-Null
  Write-Step "Started bridge in background (no window)"
}

$health = Wait-BridgeHealth
Write-Host ""
if ($health -and $health.ok) {
  Write-Host ("OK - installed once and running at http://127.0.0.1:19500 (platform=" + $health.platform + ")")
  Write-Host "It starts automatically when you sign in to Windows. You do NOT need to keep a window open."
  if ($taskOk) {
    Write-Host ("Autostart: Startup folder + Task Scheduler (" + $TaskName + ")")
  } else {
    Write-Host "Autostart: Startup folder"
  }
  Write-Host ("Logs: " + $LogPath)
  Write-Host ("To remove autostart later: " + $UninstallPath)
  Write-Host ""
  Write-Host "Go back to Palmart Cashier and click Detect printers."
} else {
  Write-Warning "Files installed, but health check failed."
  Write-Warning ('Check Node.js works: "' + $Node + '" -v')
  Write-Warning ("Log file: " + $LogPath)
  Write-Warning ("Try: " + $StartCmdPath)
  throw "Bridge did not become healthy on http://127.0.0.1:19500"
}
