# Install Palmart Till Print Bridge once on Windows 10 / 11.
# ASCII-only. PowerShell listener - no Node.js.
# Copies into %LOCALAPPDATA%, starts hidden, auto-starts at every logon.
$ErrorActionPreference = "Stop"

$PkgDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$InstallDir = Join-Path $env:LOCALAPPDATA "Palmart\till-print-bridge"
$BridgeSrc = Join-Path $PkgDir "till-print-bridge-windows.ps1"
if (-not (Test-Path $BridgeSrc)) {
  $BridgeSrc = Join-Path $PkgDir "..\till-print-bridge-windows.ps1"
}
$BridgeDst = Join-Path $InstallDir "till-print-bridge-windows.ps1"
$HelperSrc = Join-Path $PkgDir "windows-raw-print.ps1"
if (-not (Test-Path $HelperSrc)) {
  $HelperSrc = Join-Path $PkgDir "..\windows-raw-print.ps1"
}
$HelperDst = Join-Path $InstallDir "windows-raw-print.ps1"
$VbsPath = Join-Path $InstallDir "run-hidden.vbs"
$LogPath = Join-Path $InstallDir "bridge.log"
$StartCmdPath = Join-Path $InstallDir "start-till-print-bridge.cmd"
$UninstallPath = Join-Path $InstallDir "Uninstall-Palmart-Print-Bridge.ps1"
$TaskName = "PalmartTillPrintBridge"
$StartupName = "Palmart-Till-Print-Bridge.vbs"
$Port = 19500

function Write-Step([string]$Message) {
  Write-Host (" - " + $Message)
}

function Test-BridgeHealth {
  # Direct TCP so a system HTTP proxy cannot swallow 127.0.0.1
  try {
    $client = New-Object System.Net.Sockets.TcpClient
    $iar = $client.BeginConnect("127.0.0.1", $Port, $null, $null)
    $ok = $iar.AsyncWaitHandle.WaitOne(1500, $false)
    if (-not $ok) {
      try { $client.Close() } catch { }
      return $false
    }
    $client.EndConnect($iar)
    $stream = $client.GetStream()
    $req = [System.Text.Encoding]::ASCII.GetBytes("GET /health HTTP/1.1`r`nHost: 127.0.0.1`r`nConnection: close`r`n`r`n")
    $stream.Write($req, 0, $req.Length)
    $stream.Flush()
    $buf = New-Object byte[] 2048
    Start-Sleep -Milliseconds 200
    $n = 0
    try { $n = $stream.Read($buf, 0, $buf.Length) } catch { $n = 0 }
    try { $client.Close() } catch { }
    if ($n -le 0) { return $false }
    $text = [System.Text.Encoding]::ASCII.GetString($buf, 0, $n)
    return [bool]($text -match '"ok"\s*:\s*true')
  } catch {
    return $false
  }
}

function Wait-BridgeHealth([int]$Attempts = 25) {
  for ($i = 0; $i -lt $Attempts; $i++) {
    if (Test-BridgeHealth) { return $true }
    Start-Sleep -Milliseconds 700
  }
  return $false
}

function Stop-OldBridge {
  try {
    $conns = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue
    foreach ($c in $conns) {
      if ($c.OwningProcess -and $c.OwningProcess -gt 0) {
        Stop-Process -Id $c.OwningProcess -Force -ErrorAction SilentlyContinue
        Write-Step ("Stopped process on port " + $Port + " PID " + $c.OwningProcess)
      }
    }
  } catch { }

  try {
    $procs = Get-WmiObject Win32_Process -ErrorAction SilentlyContinue
    foreach ($p in @($procs)) {
      $cmd = [string]$p.CommandLine
      $name = [string]$p.Name
      if (-not $cmd) { continue }
      $hit = $false
      if ($cmd -match "till-print-bridge") { $hit = $true }
      if ($name -eq "node.exe" -and $cmd -match "till-print") { $hit = $true }
      if ($hit) {
        try {
          Stop-Process -Id $p.ProcessId -Force -ErrorAction SilentlyContinue
          Write-Step ("Stopped old bridge PID " + $p.ProcessId)
        } catch { }
      }
    }
  } catch { }
  Start-Sleep -Milliseconds 600
}

function Write-HiddenVbs([string]$PowerShellExe, [string]$BridgeFile, [string]$WorkDir, [string]$OutVbs, [string]$OutLog) {
  $psLit = $PowerShellExe.Replace('"', '')
  $bridgeLit = $BridgeFile.Replace('"', '')
  $workLit = $WorkDir.Replace('"', '')
  $logLit = $OutLog.Replace('"', '')
  $lines = @(
    "' Auto-generated by Palmart Print Bridge installer - do not edit.",
    'Set sh = CreateObject("WScript.Shell")',
    ('sh.CurrentDirectory = "' + $workLit + '"'),
    ('sh.Environment("Process")("TILL_PRINT_BRIDGE_LOG") = "' + $logLit + '"'),
    ('ps = "' + $psLit + '"'),
    ('bridge = "' + $bridgeLit + '"'),
    'cmd = Chr(34) & ps & Chr(34) & " -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File " & Chr(34) & bridge & Chr(34)',
    "' 0 = hidden window, False = do not wait",
    "sh.Run cmd, 0, False"
  )
  [System.IO.File]::WriteAllLines($OutVbs, $lines, [System.Text.Encoding]::ASCII)
}

function Install-StartupEntry([string]$SourceVbs) {
  $startupDir = [Environment]::GetFolderPath("Startup")
  if (-not $startupDir) { return $null }
  New-Item -ItemType Directory -Force -Path $startupDir | Out-Null
  $dest = Join-Path $startupDir $StartupName
  Copy-Item -Force $SourceVbs $dest
  return $dest
}

function Install-LogonTask([string]$WscriptExe, [string]$VbsFile, [string]$WorkDir) {
  $principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited
  $action = New-ScheduledTaskAction -Execute $WscriptExe -Argument ('"' + $VbsFile + '"') -WorkingDirectory $WorkDir
  $trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME

  try {
    $settings = New-ScheduledTaskSettingsSet `
      -AllowStartIfOnBatteries `
      -DontStopIfGoingOnBatteries `
      -DontStopOnIdleEnd `
      -StartWhenAvailable `
      -ExecutionTimeLimit ([TimeSpan]::Zero) `
      -RestartCount 10 `
      -RestartInterval (New-TimeSpan -Minutes 1) `
      -MultipleInstances IgnoreNew
  } catch {
    $settings = New-ScheduledTaskSettingsSet `
      -AllowStartIfOnBatteries `
      -DontStopIfGoingOnBatteries `
      -StartWhenAvailable `
      -ExecutionTimeLimit ([TimeSpan]::Zero)
  }

  Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
  Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Principal $principal `
    -Description "Palmart Till Print Bridge (127.0.0.1:19500) - PowerShell, no Node, no window" `
    -Force | Out-Null

  try {
    Start-ScheduledTask -TaskName $TaskName -ErrorAction Stop
  } catch { }
}

function Start-BridgeHidden([string]$WscriptExe, [string]$VbsFile) {
  $psi = New-Object System.Diagnostics.ProcessStartInfo
  $psi.FileName = $WscriptExe
  $psi.Arguments = '"' + $VbsFile + '"'
  $psi.WorkingDirectory = (Split-Path -Parent $VbsFile)
  $psi.WindowStyle = [System.Diagnostics.ProcessWindowStyle]::Hidden
  $psi.UseShellExecute = $true
  [void][System.Diagnostics.Process]::Start($psi)
}

if (-not (Test-Path $BridgeSrc)) {
  throw "Missing till-print-bridge-windows.ps1 next to this installer. Re-download the Windows zip."
}
if (-not (Test-Path $HelperSrc)) {
  throw "Missing windows-raw-print.ps1 next to this installer. Re-download the full Windows zip."
}

$psExe = Join-Path $env:SystemRoot "System32\WindowsPowerShell\v1.0\powershell.exe"
if (-not (Test-Path $psExe)) {
  $psExe = "powershell.exe"
}
$Wscript = Join-Path $env:SystemRoot "System32\wscript.exe"
if (-not (Test-Path $Wscript)) {
  $Wscript = "wscript.exe"
}

Write-Host ""
Write-Host "=== Palmart Till Print Bridge - Windows 10 / 11 install ==="
Write-Step ("PowerShell: " + $psExe)
Write-Step ("Install dir: " + $InstallDir)
Write-Step "No Node.js required."

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
Copy-Item -Force $BridgeSrc $BridgeDst
Copy-Item -Force $HelperSrc $HelperDst
Write-HiddenVbs -PowerShellExe $psExe -BridgeFile $BridgeDst -WorkDir $InstallDir -OutVbs $VbsPath -OutLog $LogPath
if (-not (Test-Path $VbsPath)) {
  throw ("Failed to write launcher: " + $VbsPath)
}
Write-Step ("Launcher: " + $VbsPath)

[System.IO.File]::WriteAllLines($StartCmdPath, @(
  "@echo off",
  "REM Ensures the background bridge is running (no keep-open window).",
  'cd /d "%~dp0"',
  'start "" /B wscript.exe "%~dp0run-hidden.vbs"',
  "echo Started Till Print Bridge in the background.",
  "ping -n 3 127.0.0.1 >nul"
), [System.Text.Encoding]::ASCII)

$uninstallLines = @(
  '$ErrorActionPreference = "SilentlyContinue"',
  '$InstallDir = Split-Path -Parent $MyInvocation.MyCommand.Path',
  '$TaskName = "PalmartTillPrintBridge"',
  '$Startup = Join-Path ([Environment]::GetFolderPath("Startup")) "Palmart-Till-Print-Bridge.vbs"',
  'Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false',
  'Remove-Item -Force $Startup',
  'Get-WmiObject Win32_Process | Where-Object { $_.CommandLine -match "till-print-bridge" } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }',
  'Write-Host "Stopped autostart. Remove folder to fully uninstall:" $InstallDir'
)
[System.IO.File]::WriteAllLines($UninstallPath, $uninstallLines, [System.Text.Encoding]::ASCII)

$startupPath = $null
try {
  $startupPath = Install-StartupEntry -SourceVbs $VbsPath
  if ($startupPath) { Write-Step ("Startup folder: " + $startupPath) }
} catch {
  Write-Warning ("Could not add Startup folder entry: " + $_.Exception.Message)
}

$taskOk = $false
try {
  Install-LogonTask -WscriptExe $Wscript -VbsFile $VbsPath -WorkDir $InstallDir
  $taskOk = $true
  Write-Step ("Scheduled task: " + $TaskName + " (logon, hidden, unlimited)")
} catch {
  Write-Warning ("Scheduled task not registered (Startup folder still used): " + $_.Exception.Message)
}

Stop-OldBridge
Start-BridgeHidden -WscriptExe $Wscript -VbsFile $VbsPath
Write-Step "Started bridge in background (no window)"

$ok = Wait-BridgeHealth
Write-Host ""
if ($ok) {
  Write-Host "OK - installed once and running at http://127.0.0.1:19500"
  Write-Step "printEngine=v5-bypass-epson (PowerShell, no Node.js)"
  Write-Host "It starts automatically when you sign in to Windows. You do NOT need to keep a window open."
  if ($taskOk) {
    Write-Host ("Autostart: Startup folder + Task Scheduler (" + $TaskName + ")")
  } else {
    Write-Host "Autostart: Startup folder"
  }
  Write-Host ("Logs: " + $LogPath)
  Write-Host ("To remove autostart later: " + $UninstallPath)
  Write-Host ""
  Write-Host "Go back to Palmart Cashier and click Detect printers."
  Write-Host "Detect will add the Xprinter if Windows only shows it in Device Manager."
  Write-Host "Confirm in browser: http://127.0.0.1:19500/health"
  exit 0
}

Write-Warning "Files installed, but health check failed."
Write-Warning ("Log file: " + $LogPath)
Write-Warning ("Try: " + $StartCmdPath)
Write-Warning "Then open: http://127.0.0.1:19500/health"
throw "Bridge did not become healthy on http://127.0.0.1:19500"
