export const Permission = {
  /** CSV / legacy JSON imports under Integrations (Phase 8). */
  IntegrationsImportsManage: "integrations.imports.manage",
  BusinessManageSettings: "business.manage_settings",
  UsersList: "users.list",
  UsersCreate: "users.create",
  UsersUpdate: "users.update",
  UsersDeactivate: "users.deactivate",
  UsersAssignRole: "users.assign_role",
  CatalogItemsRead: "catalog.items.read",
  CatalogItemsWrite: "catalog.items.write",
  CatalogCategoriesWrite: "catalog.categories.write",
  CatalogItemsLinkSuppliers: "catalog.items.link_suppliers",
  PurchasingIntelligenceRead: "purchasing.intelligence.read",
  PurchasingPathBRead: "purchasing.path_b.read",
  PurchasingPathBWrite: "purchasing.path_b.write",
  PurchasingPaymentRead: "purchasing.payment.read",
  PurchasingPaymentWrite: "purchasing.payment.write",
  SuppliersRead: "suppliers.read",
  SuppliersWrite: "suppliers.write",
  InventoryRead: "inventory.read",
  InventoryWrite: "inventory.write",
  InventoryTransfer: "inventory.transfer",
  StocktakeRead: "stocktake.read",
  StocktakeRun: "stocktake.run",
  StocktakeApprove: "stocktake.approve",
  PricingRead: "pricing.read",
  PricingSellPriceSet: "pricing.sell_price.set",
  PricingRulesManage: "pricing.rules.manage",
  ShiftsOpen: "shifts.open",
  ShiftsClose: "shifts.close",
  ShiftsRead: "shifts.read",
  SalesSell: "sales.sell",
  SalesVoidOwn: "sales.void.own",
  SalesVoidAny: "sales.void.any",
  SalesRefundCreate: "sales.refund.create",
  SalesIntelligenceRead: "sales.intelligence.read",
  StorefrontOrdersRead: "storefront.orders.read",
  CreditsCustomersRead: "credits.customers.read",
  CreditsCustomersWrite: "credits.customers.write",
  CreditsWalletWrite: "credits.wallet.write",
  CreditsClaimsIssue: "credits.claims.issue",
  CreditsClaimsReview: "credits.claims.review",
  PaymentsStkInitiate: "payments.stk.initiate",
} as const;

export function hasPermission(
  permissions: string[] | undefined,
  key: string,
): boolean {
  return permissions?.includes(key) ?? false;
}
