/**
 * Mirrors backend classpath:region-profiles.csv (+ locality overrides).
 * Generated for desktop setup / offline fallback — do not hand-edit; regenerate
 * from scripts/generate-world-region-defaults.mjs when the CSV changes.
 */
export type WorldRegionDefault = {
  countryCode: string;
  label: string;
  currency: string;
  timezone: string;
  dialCode: string;
  defaultVatPercent: number;
  localityPlaceholders: readonly string[];
};

export const WORLD_REGION_DEFAULTS: readonly WorldRegionDefault[] = [
  {
    countryCode: "AF",
    label: "Afghanistan",
    currency: "AFN",
    timezone: "Asia/Kabul",
    dialCode: "+93",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "AX",
    label: "Åland Islands",
    currency: "EUR",
    timezone: "Europe/Mariehamn",
    dialCode: "+358",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "AL",
    label: "Albania",
    currency: "ALL",
    timezone: "Europe/Tirane",
    dialCode: "+355",
    defaultVatPercent: 20,
    localityPlaceholders: [],
  },
  {
    countryCode: "DZ",
    label: "Algeria",
    currency: "DZD",
    timezone: "Africa/Algiers",
    dialCode: "+213",
    defaultVatPercent: 19,
    localityPlaceholders: [],
  },
  {
    countryCode: "AS",
    label: "American Samoa",
    currency: "USD",
    timezone: "Pacific/Pago_Pago",
    dialCode: "+1684",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "AD",
    label: "Andorra",
    currency: "EUR",
    timezone: "Europe/Andorra",
    dialCode: "+376",
    defaultVatPercent: 4.5,
    localityPlaceholders: [],
  },
  {
    countryCode: "AO",
    label: "Angola",
    currency: "AOA",
    timezone: "Africa/Luanda",
    dialCode: "+244",
    defaultVatPercent: 14,
    localityPlaceholders: [],
  },
  {
    countryCode: "AI",
    label: "Anguilla",
    currency: "XCD",
    timezone: "America/Anguilla",
    dialCode: "+1264",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "AQ",
    label: "Antarctica",
    currency: "USD",
    timezone: "UTC",
    dialCode: "+672",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "AG",
    label: "Antigua and Barbuda",
    currency: "XCD",
    timezone: "America/Antigua",
    dialCode: "+1268",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "AR",
    label: "Argentina",
    currency: "ARS",
    timezone: "America/Argentina/Buenos_Aires",
    dialCode: "+54",
    defaultVatPercent: 21,
    localityPlaceholders: [],
  },
  {
    countryCode: "AM",
    label: "Armenia",
    currency: "AMD",
    timezone: "Asia/Yerevan",
    dialCode: "+374",
    defaultVatPercent: 20,
    localityPlaceholders: [],
  },
  {
    countryCode: "AW",
    label: "Aruba",
    currency: "AWG",
    timezone: "America/Aruba",
    dialCode: "+297",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "AU",
    label: "Australia",
    currency: "AUD",
    timezone: "Australia/Sydney",
    dialCode: "+61",
    defaultVatPercent: 10,
    localityPlaceholders: [],
  },
  {
    countryCode: "AT",
    label: "Austria",
    currency: "EUR",
    timezone: "Europe/Vienna",
    dialCode: "+43",
    defaultVatPercent: 20,
    localityPlaceholders: [],
  },
  {
    countryCode: "AZ",
    label: "Azerbaijan",
    currency: "AZN",
    timezone: "Asia/Baku",
    dialCode: "+994",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "BS",
    label: "Bahamas",
    currency: "BSD",
    timezone: "America/Nassau",
    dialCode: "+1242",
    defaultVatPercent: 12,
    localityPlaceholders: [],
  },
  {
    countryCode: "BH",
    label: "Bahrain",
    currency: "BHD",
    timezone: "Asia/Bahrain",
    dialCode: "+973",
    defaultVatPercent: 10,
    localityPlaceholders: [],
  },
  {
    countryCode: "BD",
    label: "Bangladesh",
    currency: "BDT",
    timezone: "Asia/Dhaka",
    dialCode: "+880",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "BB",
    label: "Barbados",
    currency: "BBD",
    timezone: "America/Barbados",
    dialCode: "+1246",
    defaultVatPercent: 17.5,
    localityPlaceholders: [],
  },
  {
    countryCode: "BY",
    label: "Belarus",
    currency: "BYN",
    timezone: "Europe/Minsk",
    dialCode: "+375",
    defaultVatPercent: 20,
    localityPlaceholders: [],
  },
  {
    countryCode: "BE",
    label: "Belgium",
    currency: "EUR",
    timezone: "Europe/Brussels",
    dialCode: "+32",
    defaultVatPercent: 21,
    localityPlaceholders: [],
  },
  {
    countryCode: "BZ",
    label: "Belize",
    currency: "BZD",
    timezone: "America/Belize",
    dialCode: "+501",
    defaultVatPercent: 12.5,
    localityPlaceholders: [],
  },
  {
    countryCode: "BJ",
    label: "Benin",
    currency: "XOF",
    timezone: "Africa/Porto-Novo",
    dialCode: "+229",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "BM",
    label: "Bermuda",
    currency: "BMD",
    timezone: "Atlantic/Bermuda",
    dialCode: "+1441",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "BT",
    label: "Bhutan",
    currency: "BTN",
    timezone: "Asia/Thimphu",
    dialCode: "+975",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "BO",
    label: "Bolivia",
    currency: "BOB",
    timezone: "America/La_Paz",
    dialCode: "+591",
    defaultVatPercent: 13,
    localityPlaceholders: [],
  },
  {
    countryCode: "BQ",
    label: "Bonaire, Sint Eustatius and Saba",
    currency: "USD",
    timezone: "America/Kralendijk",
    dialCode: "+599",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "BA",
    label: "Bosnia and Herzegovina",
    currency: "BAM",
    timezone: "Europe/Sarajevo",
    dialCode: "+387",
    defaultVatPercent: 17,
    localityPlaceholders: [],
  },
  {
    countryCode: "BW",
    label: "Botswana",
    currency: "BWP",
    timezone: "Africa/Gaborone",
    dialCode: "+267",
    defaultVatPercent: 14,
    localityPlaceholders: [],
  },
  {
    countryCode: "BV",
    label: "Bouvet Island",
    currency: "NOK",
    timezone: "UTC",
    dialCode: "+47",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "BR",
    label: "Brazil",
    currency: "BRL",
    timezone: "America/Sao_Paulo",
    dialCode: "+55",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "IO",
    label: "British Indian Ocean Territory",
    currency: "USD",
    timezone: "Indian/Chagos",
    dialCode: "+246",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "VG",
    label: "British Virgin Islands",
    currency: "USD",
    timezone: "America/Tortola",
    dialCode: "+1284",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "BN",
    label: "Brunei",
    currency: "BND",
    timezone: "Asia/Brunei",
    dialCode: "+673",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "BG",
    label: "Bulgaria",
    currency: "BGN",
    timezone: "Europe/Sofia",
    dialCode: "+359",
    defaultVatPercent: 20,
    localityPlaceholders: [],
  },
  {
    countryCode: "BF",
    label: "Burkina Faso",
    currency: "XOF",
    timezone: "Africa/Ouagadougou",
    dialCode: "+226",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "BI",
    label: "Burundi",
    currency: "BIF",
    timezone: "Africa/Bujumbura",
    dialCode: "+257",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "CV",
    label: "Cabo Verde",
    currency: "CVE",
    timezone: "Atlantic/Cape_Verde",
    dialCode: "+238",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "KH",
    label: "Cambodia",
    currency: "KHR",
    timezone: "Asia/Phnom_Penh",
    dialCode: "+855",
    defaultVatPercent: 10,
    localityPlaceholders: [],
  },
  {
    countryCode: "CM",
    label: "Cameroon",
    currency: "XAF",
    timezone: "Africa/Douala",
    dialCode: "+237",
    defaultVatPercent: 19.25,
    localityPlaceholders: [],
  },
  {
    countryCode: "CA",
    label: "Canada",
    currency: "CAD",
    timezone: "America/Toronto",
    dialCode: "+1",
    defaultVatPercent: 5,
    localityPlaceholders: [],
  },
  {
    countryCode: "KY",
    label: "Cayman Islands",
    currency: "KYD",
    timezone: "America/Cayman",
    dialCode: "+1345",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "CF",
    label: "Central African Republic",
    currency: "XAF",
    timezone: "Africa/Bangui",
    dialCode: "+236",
    defaultVatPercent: 19,
    localityPlaceholders: [],
  },
  {
    countryCode: "TD",
    label: "Chad",
    currency: "XAF",
    timezone: "Africa/Ndjamena",
    dialCode: "+235",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "CL",
    label: "Chile",
    currency: "CLP",
    timezone: "America/Santiago",
    dialCode: "+56",
    defaultVatPercent: 19,
    localityPlaceholders: [],
  },
  {
    countryCode: "CN",
    label: "China",
    currency: "CNY",
    timezone: "Asia/Shanghai",
    dialCode: "+86",
    defaultVatPercent: 13,
    localityPlaceholders: [],
  },
  {
    countryCode: "CX",
    label: "Christmas Island",
    currency: "AUD",
    timezone: "Indian/Christmas",
    dialCode: "+61",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "CC",
    label: "Cocos (Keeling) Islands",
    currency: "AUD",
    timezone: "Indian/Cocos",
    dialCode: "+61",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "CO",
    label: "Colombia",
    currency: "COP",
    timezone: "America/Bogota",
    dialCode: "+57",
    defaultVatPercent: 19,
    localityPlaceholders: [],
  },
  {
    countryCode: "KM",
    label: "Comoros",
    currency: "KMF",
    timezone: "Indian/Comoro",
    dialCode: "+269",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "CG",
    label: "Congo",
    currency: "XAF",
    timezone: "Africa/Brazzaville",
    dialCode: "+242",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "CD",
    label: "Congo (DRC)",
    currency: "CDF",
    timezone: "Africa/Kinshasa",
    dialCode: "+243",
    defaultVatPercent: 16,
    localityPlaceholders: [],
  },
  {
    countryCode: "CK",
    label: "Cook Islands",
    currency: "NZD",
    timezone: "Pacific/Rarotonga",
    dialCode: "+682",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "CR",
    label: "Costa Rica",
    currency: "CRC",
    timezone: "America/Costa_Rica",
    dialCode: "+506",
    defaultVatPercent: 13,
    localityPlaceholders: [],
  },
  {
    countryCode: "CI",
    label: "Côte d'Ivoire",
    currency: "XOF",
    timezone: "Africa/Abidjan",
    dialCode: "+225",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "HR",
    label: "Croatia",
    currency: "EUR",
    timezone: "Europe/Zagreb",
    dialCode: "+385",
    defaultVatPercent: 25,
    localityPlaceholders: [],
  },
  {
    countryCode: "CU",
    label: "Cuba",
    currency: "CUP",
    timezone: "America/Havana",
    dialCode: "+53",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "CW",
    label: "Curaçao",
    currency: "ANG",
    timezone: "America/Curacao",
    dialCode: "+599",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "CY",
    label: "Cyprus",
    currency: "EUR",
    timezone: "Asia/Nicosia",
    dialCode: "+357",
    defaultVatPercent: 19,
    localityPlaceholders: [],
  },
  {
    countryCode: "CZ",
    label: "Czechia",
    currency: "CZK",
    timezone: "Europe/Prague",
    dialCode: "+420",
    defaultVatPercent: 21,
    localityPlaceholders: [],
  },
  {
    countryCode: "DK",
    label: "Denmark",
    currency: "DKK",
    timezone: "Europe/Copenhagen",
    dialCode: "+45",
    defaultVatPercent: 25,
    localityPlaceholders: [],
  },
  {
    countryCode: "DJ",
    label: "Djibouti",
    currency: "DJF",
    timezone: "Africa/Djibouti",
    dialCode: "+253",
    defaultVatPercent: 10,
    localityPlaceholders: [],
  },
  {
    countryCode: "DM",
    label: "Dominica",
    currency: "XCD",
    timezone: "America/Dominica",
    dialCode: "+1767",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "DO",
    label: "Dominican Republic",
    currency: "DOP",
    timezone: "America/Santo_Domingo",
    dialCode: "+1809",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "EC",
    label: "Ecuador",
    currency: "USD",
    timezone: "America/Guayaquil",
    dialCode: "+593",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "EG",
    label: "Egypt",
    currency: "EGP",
    timezone: "Africa/Cairo",
    dialCode: "+20",
    defaultVatPercent: 14,
    localityPlaceholders: [],
  },
  {
    countryCode: "SV",
    label: "El Salvador",
    currency: "USD",
    timezone: "America/El_Salvador",
    dialCode: "+503",
    defaultVatPercent: 13,
    localityPlaceholders: [],
  },
  {
    countryCode: "GQ",
    label: "Equatorial Guinea",
    currency: "XAF",
    timezone: "Africa/Malabo",
    dialCode: "+240",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "ER",
    label: "Eritrea",
    currency: "ERN",
    timezone: "Africa/Asmara",
    dialCode: "+291",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "EE",
    label: "Estonia",
    currency: "EUR",
    timezone: "Europe/Tallinn",
    dialCode: "+372",
    defaultVatPercent: 22,
    localityPlaceholders: [],
  },
  {
    countryCode: "SZ",
    label: "Eswatini",
    currency: "SZL",
    timezone: "Africa/Mbabane",
    dialCode: "+268",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "ET",
    label: "Ethiopia",
    currency: "ETB",
    timezone: "Africa/Addis_Ababa",
    dialCode: "+251",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "FK",
    label: "Falkland Islands",
    currency: "FKP",
    timezone: "Atlantic/Stanley",
    dialCode: "+500",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "FO",
    label: "Faroe Islands",
    currency: "DKK",
    timezone: "Atlantic/Faroe",
    dialCode: "+298",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "FJ",
    label: "Fiji",
    currency: "FJD",
    timezone: "Pacific/Fiji",
    dialCode: "+679",
    defaultVatPercent: 9,
    localityPlaceholders: [],
  },
  {
    countryCode: "FI",
    label: "Finland",
    currency: "EUR",
    timezone: "Europe/Helsinki",
    dialCode: "+358",
    defaultVatPercent: 24,
    localityPlaceholders: [],
  },
  {
    countryCode: "FR",
    label: "France",
    currency: "EUR",
    timezone: "Europe/Paris",
    dialCode: "+33",
    defaultVatPercent: 20,
    localityPlaceholders: [],
  },
  {
    countryCode: "GF",
    label: "French Guiana",
    currency: "EUR",
    timezone: "America/Cayenne",
    dialCode: "+594",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "PF",
    label: "French Polynesia",
    currency: "XPF",
    timezone: "Pacific/Tahiti",
    dialCode: "+689",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "TF",
    label: "French Southern Territories",
    currency: "EUR",
    timezone: "Indian/Kerguelen",
    dialCode: "+262",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "GA",
    label: "Gabon",
    currency: "XAF",
    timezone: "Africa/Libreville",
    dialCode: "+241",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "GM",
    label: "Gambia",
    currency: "GMD",
    timezone: "Africa/Banjul",
    dialCode: "+220",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "GE",
    label: "Georgia",
    currency: "GEL",
    timezone: "Asia/Tbilisi",
    dialCode: "+995",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "DE",
    label: "Germany",
    currency: "EUR",
    timezone: "Europe/Berlin",
    dialCode: "+49",
    defaultVatPercent: 19,
    localityPlaceholders: [],
  },
  {
    countryCode: "GH",
    label: "Ghana",
    currency: "GHS",
    timezone: "Africa/Accra",
    dialCode: "+233",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "GI",
    label: "Gibraltar",
    currency: "GIP",
    timezone: "Europe/Gibraltar",
    dialCode: "+350",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "GR",
    label: "Greece",
    currency: "EUR",
    timezone: "Europe/Athens",
    dialCode: "+30",
    defaultVatPercent: 24,
    localityPlaceholders: [],
  },
  {
    countryCode: "GL",
    label: "Greenland",
    currency: "DKK",
    timezone: "America/Godthab",
    dialCode: "+299",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "GD",
    label: "Grenada",
    currency: "XCD",
    timezone: "America/Grenada",
    dialCode: "+1473",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "GP",
    label: "Guadeloupe",
    currency: "EUR",
    timezone: "America/Guadeloupe",
    dialCode: "+590",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "GU",
    label: "Guam",
    currency: "USD",
    timezone: "Pacific/Guam",
    dialCode: "+1671",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "GT",
    label: "Guatemala",
    currency: "GTQ",
    timezone: "America/Guatemala",
    dialCode: "+502",
    defaultVatPercent: 12,
    localityPlaceholders: [],
  },
  {
    countryCode: "GG",
    label: "Guernsey",
    currency: "GBP",
    timezone: "Europe/Guernsey",
    dialCode: "+44",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "GN",
    label: "Guinea",
    currency: "GNF",
    timezone: "Africa/Conakry",
    dialCode: "+224",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "GW",
    label: "Guinea-Bissau",
    currency: "XOF",
    timezone: "Africa/Bissau",
    dialCode: "+245",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "GY",
    label: "Guyana",
    currency: "GYD",
    timezone: "America/Guyana",
    dialCode: "+592",
    defaultVatPercent: 14,
    localityPlaceholders: [],
  },
  {
    countryCode: "HT",
    label: "Haiti",
    currency: "HTG",
    timezone: "America/Port-au-Prince",
    dialCode: "+509",
    defaultVatPercent: 10,
    localityPlaceholders: [],
  },
  {
    countryCode: "HM",
    label: "Heard Island and McDonald Islands",
    currency: "AUD",
    timezone: "UTC",
    dialCode: "+672",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "HN",
    label: "Honduras",
    currency: "HNL",
    timezone: "America/Tegucigalpa",
    dialCode: "+504",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "HK",
    label: "Hong Kong",
    currency: "HKD",
    timezone: "Asia/Hong_Kong",
    dialCode: "+852",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "HU",
    label: "Hungary",
    currency: "HUF",
    timezone: "Europe/Budapest",
    dialCode: "+36",
    defaultVatPercent: 27,
    localityPlaceholders: [],
  },
  {
    countryCode: "IS",
    label: "Iceland",
    currency: "ISK",
    timezone: "Atlantic/Reykjavik",
    dialCode: "+354",
    defaultVatPercent: 24,
    localityPlaceholders: [],
  },
  {
    countryCode: "IN",
    label: "India",
    currency: "INR",
    timezone: "Asia/Kolkata",
    dialCode: "+91",
    defaultVatPercent: 18,
    localityPlaceholders: ["Mumbai","Delhi","Bengaluru","Hyderabad","Chennai"],
  },
  {
    countryCode: "ID",
    label: "Indonesia",
    currency: "IDR",
    timezone: "Asia/Jakarta",
    dialCode: "+62",
    defaultVatPercent: 11,
    localityPlaceholders: [],
  },
  {
    countryCode: "IR",
    label: "Iran",
    currency: "IRR",
    timezone: "Asia/Tehran",
    dialCode: "+98",
    defaultVatPercent: 9,
    localityPlaceholders: [],
  },
  {
    countryCode: "IQ",
    label: "Iraq",
    currency: "IQD",
    timezone: "Asia/Baghdad",
    dialCode: "+964",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "IE",
    label: "Ireland",
    currency: "EUR",
    timezone: "Europe/Dublin",
    dialCode: "+353",
    defaultVatPercent: 23,
    localityPlaceholders: [],
  },
  {
    countryCode: "IM",
    label: "Isle of Man",
    currency: "GBP",
    timezone: "Europe/Isle_of_Man",
    dialCode: "+44",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "IL",
    label: "Israel",
    currency: "ILS",
    timezone: "Asia/Jerusalem",
    dialCode: "+972",
    defaultVatPercent: 17,
    localityPlaceholders: [],
  },
  {
    countryCode: "IT",
    label: "Italy",
    currency: "EUR",
    timezone: "Europe/Rome",
    dialCode: "+39",
    defaultVatPercent: 22,
    localityPlaceholders: [],
  },
  {
    countryCode: "JM",
    label: "Jamaica",
    currency: "JMD",
    timezone: "America/Jamaica",
    dialCode: "+1876",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "JP",
    label: "Japan",
    currency: "JPY",
    timezone: "Asia/Tokyo",
    dialCode: "+81",
    defaultVatPercent: 10,
    localityPlaceholders: [],
  },
  {
    countryCode: "JE",
    label: "Jersey",
    currency: "GBP",
    timezone: "Europe/Jersey",
    dialCode: "+44",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "JO",
    label: "Jordan",
    currency: "JOD",
    timezone: "Asia/Amman",
    dialCode: "+962",
    defaultVatPercent: 16,
    localityPlaceholders: [],
  },
  {
    countryCode: "KZ",
    label: "Kazakhstan",
    currency: "KZT",
    timezone: "Asia/Almaty",
    dialCode: "+7",
    defaultVatPercent: 12,
    localityPlaceholders: [],
  },
  {
    countryCode: "KE",
    label: "Kenya",
    currency: "KES",
    timezone: "Africa/Nairobi",
    dialCode: "+254",
    defaultVatPercent: 16,
    localityPlaceholders: ["Mirema","Kasarani","Ongata Rongai","Westlands","Karen"],
  },
  {
    countryCode: "KI",
    label: "Kiribati",
    currency: "AUD",
    timezone: "Pacific/Tarawa",
    dialCode: "+686",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "XK",
    label: "Kosovo",
    currency: "EUR",
    timezone: "Europe/Belgrade",
    dialCode: "+383",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "KW",
    label: "Kuwait",
    currency: "KWD",
    timezone: "Asia/Kuwait",
    dialCode: "+965",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "KG",
    label: "Kyrgyzstan",
    currency: "KGS",
    timezone: "Asia/Bishkek",
    dialCode: "+996",
    defaultVatPercent: 12,
    localityPlaceholders: [],
  },
  {
    countryCode: "LA",
    label: "Laos",
    currency: "LAK",
    timezone: "Asia/Vientiane",
    dialCode: "+856",
    defaultVatPercent: 10,
    localityPlaceholders: [],
  },
  {
    countryCode: "LV",
    label: "Latvia",
    currency: "EUR",
    timezone: "Europe/Riga",
    dialCode: "+371",
    defaultVatPercent: 21,
    localityPlaceholders: [],
  },
  {
    countryCode: "LB",
    label: "Lebanon",
    currency: "LBP",
    timezone: "Asia/Beirut",
    dialCode: "+961",
    defaultVatPercent: 11,
    localityPlaceholders: [],
  },
  {
    countryCode: "LS",
    label: "Lesotho",
    currency: "LSL",
    timezone: "Africa/Maseru",
    dialCode: "+266",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "LR",
    label: "Liberia",
    currency: "LRD",
    timezone: "Africa/Monrovia",
    dialCode: "+231",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "LY",
    label: "Libya",
    currency: "LYD",
    timezone: "Africa/Tripoli",
    dialCode: "+218",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "LI",
    label: "Liechtenstein",
    currency: "CHF",
    timezone: "Europe/Vaduz",
    dialCode: "+423",
    defaultVatPercent: 8.1,
    localityPlaceholders: [],
  },
  {
    countryCode: "LT",
    label: "Lithuania",
    currency: "EUR",
    timezone: "Europe/Vilnius",
    dialCode: "+370",
    defaultVatPercent: 21,
    localityPlaceholders: [],
  },
  {
    countryCode: "LU",
    label: "Luxembourg",
    currency: "EUR",
    timezone: "Europe/Luxembourg",
    dialCode: "+352",
    defaultVatPercent: 17,
    localityPlaceholders: [],
  },
  {
    countryCode: "MO",
    label: "Macao",
    currency: "MOP",
    timezone: "Asia/Macau",
    dialCode: "+853",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "MG",
    label: "Madagascar",
    currency: "MGA",
    timezone: "Indian/Antananarivo",
    dialCode: "+261",
    defaultVatPercent: 20,
    localityPlaceholders: [],
  },
  {
    countryCode: "MW",
    label: "Malawi",
    currency: "MWK",
    timezone: "Africa/Blantyre",
    dialCode: "+265",
    defaultVatPercent: 16.5,
    localityPlaceholders: [],
  },
  {
    countryCode: "MY",
    label: "Malaysia",
    currency: "MYR",
    timezone: "Asia/Kuala_Lumpur",
    dialCode: "+60",
    defaultVatPercent: 8,
    localityPlaceholders: [],
  },
  {
    countryCode: "MV",
    label: "Maldives",
    currency: "MVR",
    timezone: "Indian/Maldives",
    dialCode: "+960",
    defaultVatPercent: 8,
    localityPlaceholders: [],
  },
  {
    countryCode: "ML",
    label: "Mali",
    currency: "XOF",
    timezone: "Africa/Bamako",
    dialCode: "+223",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "MT",
    label: "Malta",
    currency: "EUR",
    timezone: "Europe/Malta",
    dialCode: "+356",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "MH",
    label: "Marshall Islands",
    currency: "USD",
    timezone: "Pacific/Majuro",
    dialCode: "+692",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "MQ",
    label: "Martinique",
    currency: "EUR",
    timezone: "America/Martinique",
    dialCode: "+596",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "MR",
    label: "Mauritania",
    currency: "MRU",
    timezone: "Africa/Nouakchott",
    dialCode: "+222",
    defaultVatPercent: 16,
    localityPlaceholders: [],
  },
  {
    countryCode: "MU",
    label: "Mauritius",
    currency: "MUR",
    timezone: "Indian/Mauritius",
    dialCode: "+230",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "YT",
    label: "Mayotte",
    currency: "EUR",
    timezone: "Indian/Mayotte",
    dialCode: "+262",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "MX",
    label: "Mexico",
    currency: "MXN",
    timezone: "America/Mexico_City",
    dialCode: "+52",
    defaultVatPercent: 16,
    localityPlaceholders: [],
  },
  {
    countryCode: "FM",
    label: "Micronesia",
    currency: "USD",
    timezone: "Pacific/Chuuk",
    dialCode: "+691",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "MD",
    label: "Moldova",
    currency: "MDL",
    timezone: "Europe/Chisinau",
    dialCode: "+373",
    defaultVatPercent: 20,
    localityPlaceholders: [],
  },
  {
    countryCode: "MC",
    label: "Monaco",
    currency: "EUR",
    timezone: "Europe/Monaco",
    dialCode: "+377",
    defaultVatPercent: 20,
    localityPlaceholders: [],
  },
  {
    countryCode: "MN",
    label: "Mongolia",
    currency: "MNT",
    timezone: "Asia/Ulaanbaatar",
    dialCode: "+976",
    defaultVatPercent: 10,
    localityPlaceholders: [],
  },
  {
    countryCode: "ME",
    label: "Montenegro",
    currency: "EUR",
    timezone: "Europe/Podgorica",
    dialCode: "+382",
    defaultVatPercent: 21,
    localityPlaceholders: [],
  },
  {
    countryCode: "MS",
    label: "Montserrat",
    currency: "XCD",
    timezone: "America/Montserrat",
    dialCode: "+1664",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "MA",
    label: "Morocco",
    currency: "MAD",
    timezone: "Africa/Casablanca",
    dialCode: "+212",
    defaultVatPercent: 20,
    localityPlaceholders: [],
  },
  {
    countryCode: "MZ",
    label: "Mozambique",
    currency: "MZN",
    timezone: "Africa/Maputo",
    dialCode: "+258",
    defaultVatPercent: 17,
    localityPlaceholders: [],
  },
  {
    countryCode: "MM",
    label: "Myanmar",
    currency: "MMK",
    timezone: "Asia/Yangon",
    dialCode: "+95",
    defaultVatPercent: 5,
    localityPlaceholders: [],
  },
  {
    countryCode: "NA",
    label: "Namibia",
    currency: "NAD",
    timezone: "Africa/Windhoek",
    dialCode: "+264",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "NR",
    label: "Nauru",
    currency: "AUD",
    timezone: "Pacific/Nauru",
    dialCode: "+674",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "NP",
    label: "Nepal",
    currency: "NPR",
    timezone: "Asia/Kathmandu",
    dialCode: "+977",
    defaultVatPercent: 13,
    localityPlaceholders: [],
  },
  {
    countryCode: "NL",
    label: "Netherlands",
    currency: "EUR",
    timezone: "Europe/Amsterdam",
    dialCode: "+31",
    defaultVatPercent: 21,
    localityPlaceholders: [],
  },
  {
    countryCode: "NC",
    label: "New Caledonia",
    currency: "XPF",
    timezone: "Pacific/Noumea",
    dialCode: "+687",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "NZ",
    label: "New Zealand",
    currency: "NZD",
    timezone: "Pacific/Auckland",
    dialCode: "+64",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "NI",
    label: "Nicaragua",
    currency: "NIO",
    timezone: "America/Managua",
    dialCode: "+505",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "NE",
    label: "Niger",
    currency: "XOF",
    timezone: "Africa/Niamey",
    dialCode: "+227",
    defaultVatPercent: 19,
    localityPlaceholders: [],
  },
  {
    countryCode: "NG",
    label: "Nigeria",
    currency: "NGN",
    timezone: "Africa/Lagos",
    dialCode: "+234",
    defaultVatPercent: 7.5,
    localityPlaceholders: ["Lagos","Abuja","Port Harcourt","Ibadan","Kano"],
  },
  {
    countryCode: "NU",
    label: "Niue",
    currency: "NZD",
    timezone: "Pacific/Niue",
    dialCode: "+683",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "NF",
    label: "Norfolk Island",
    currency: "AUD",
    timezone: "Pacific/Norfolk",
    dialCode: "+672",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "KP",
    label: "North Korea",
    currency: "KPW",
    timezone: "Asia/Pyongyang",
    dialCode: "+850",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "MK",
    label: "North Macedonia",
    currency: "MKD",
    timezone: "Europe/Skopje",
    dialCode: "+389",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "MP",
    label: "Northern Mariana Islands",
    currency: "USD",
    timezone: "Pacific/Saipan",
    dialCode: "+1670",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "NO",
    label: "Norway",
    currency: "NOK",
    timezone: "Europe/Oslo",
    dialCode: "+47",
    defaultVatPercent: 25,
    localityPlaceholders: [],
  },
  {
    countryCode: "OM",
    label: "Oman",
    currency: "OMR",
    timezone: "Asia/Muscat",
    dialCode: "+968",
    defaultVatPercent: 5,
    localityPlaceholders: [],
  },
  {
    countryCode: "PK",
    label: "Pakistan",
    currency: "PKR",
    timezone: "Asia/Karachi",
    dialCode: "+92",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "PW",
    label: "Palau",
    currency: "USD",
    timezone: "Pacific/Palau",
    dialCode: "+680",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "PS",
    label: "Palestine",
    currency: "ILS",
    timezone: "Asia/Gaza",
    dialCode: "+970",
    defaultVatPercent: 16,
    localityPlaceholders: [],
  },
  {
    countryCode: "PA",
    label: "Panama",
    currency: "PAB",
    timezone: "America/Panama",
    dialCode: "+507",
    defaultVatPercent: 7,
    localityPlaceholders: [],
  },
  {
    countryCode: "PG",
    label: "Papua New Guinea",
    currency: "PGK",
    timezone: "Pacific/Port_Moresby",
    dialCode: "+675",
    defaultVatPercent: 10,
    localityPlaceholders: [],
  },
  {
    countryCode: "PY",
    label: "Paraguay",
    currency: "PYG",
    timezone: "America/Asuncion",
    dialCode: "+595",
    defaultVatPercent: 10,
    localityPlaceholders: [],
  },
  {
    countryCode: "PE",
    label: "Peru",
    currency: "PEN",
    timezone: "America/Lima",
    dialCode: "+51",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "PH",
    label: "Philippines",
    currency: "PHP",
    timezone: "Asia/Manila",
    dialCode: "+63",
    defaultVatPercent: 12,
    localityPlaceholders: [],
  },
  {
    countryCode: "PN",
    label: "Pitcairn Islands",
    currency: "NZD",
    timezone: "Pacific/Pitcairn",
    dialCode: "+64",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "PL",
    label: "Poland",
    currency: "PLN",
    timezone: "Europe/Warsaw",
    dialCode: "+48",
    defaultVatPercent: 23,
    localityPlaceholders: [],
  },
  {
    countryCode: "PT",
    label: "Portugal",
    currency: "EUR",
    timezone: "Europe/Lisbon",
    dialCode: "+351",
    defaultVatPercent: 23,
    localityPlaceholders: [],
  },
  {
    countryCode: "PR",
    label: "Puerto Rico",
    currency: "USD",
    timezone: "America/Puerto_Rico",
    dialCode: "+1787",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "QA",
    label: "Qatar",
    currency: "QAR",
    timezone: "Asia/Qatar",
    dialCode: "+974",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "RE",
    label: "Réunion",
    currency: "EUR",
    timezone: "Indian/Reunion",
    dialCode: "+262",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "RO",
    label: "Romania",
    currency: "RON",
    timezone: "Europe/Bucharest",
    dialCode: "+40",
    defaultVatPercent: 19,
    localityPlaceholders: [],
  },
  {
    countryCode: "RU",
    label: "Russia",
    currency: "RUB",
    timezone: "Europe/Moscow",
    dialCode: "+7",
    defaultVatPercent: 20,
    localityPlaceholders: [],
  },
  {
    countryCode: "RW",
    label: "Rwanda",
    currency: "RWF",
    timezone: "Africa/Kigali",
    dialCode: "+250",
    defaultVatPercent: 18,
    localityPlaceholders: ["Kigali","Butare","Gisenyi","Ruhengeri","Musanze"],
  },
  {
    countryCode: "BL",
    label: "Saint Barthélemy",
    currency: "EUR",
    timezone: "America/St_Barthelemy",
    dialCode: "+590",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "SH",
    label: "Saint Helena",
    currency: "SHP",
    timezone: "Atlantic/St_Helena",
    dialCode: "+290",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "KN",
    label: "Saint Kitts and Nevis",
    currency: "XCD",
    timezone: "America/St_Kitts",
    dialCode: "+1869",
    defaultVatPercent: 17,
    localityPlaceholders: [],
  },
  {
    countryCode: "LC",
    label: "Saint Lucia",
    currency: "XCD",
    timezone: "America/St_Lucia",
    dialCode: "+1758",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "MF",
    label: "Saint Martin",
    currency: "EUR",
    timezone: "America/Marigot",
    dialCode: "+590",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "PM",
    label: "Saint Pierre and Miquelon",
    currency: "EUR",
    timezone: "America/Miquelon",
    dialCode: "+508",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "VC",
    label: "Saint Vincent and the Grenadines",
    currency: "XCD",
    timezone: "America/St_Vincent",
    dialCode: "+1784",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "WS",
    label: "Samoa",
    currency: "WST",
    timezone: "Pacific/Apia",
    dialCode: "+685",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "SM",
    label: "San Marino",
    currency: "EUR",
    timezone: "Europe/San_Marino",
    dialCode: "+378",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "ST",
    label: "São Tomé and Príncipe",
    currency: "STN",
    timezone: "Africa/Sao_Tome",
    dialCode: "+239",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "SA",
    label: "Saudi Arabia",
    currency: "SAR",
    timezone: "Asia/Riyadh",
    dialCode: "+966",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "SN",
    label: "Senegal",
    currency: "XOF",
    timezone: "Africa/Dakar",
    dialCode: "+221",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "RS",
    label: "Serbia",
    currency: "RSD",
    timezone: "Europe/Belgrade",
    dialCode: "+381",
    defaultVatPercent: 20,
    localityPlaceholders: [],
  },
  {
    countryCode: "SC",
    label: "Seychelles",
    currency: "SCR",
    timezone: "Indian/Mahe",
    dialCode: "+248",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "SL",
    label: "Sierra Leone",
    currency: "SLE",
    timezone: "Africa/Freetown",
    dialCode: "+232",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "SG",
    label: "Singapore",
    currency: "SGD",
    timezone: "Asia/Singapore",
    dialCode: "+65",
    defaultVatPercent: 9,
    localityPlaceholders: [],
  },
  {
    countryCode: "SX",
    label: "Sint Maarten",
    currency: "ANG",
    timezone: "America/Lower_Princes",
    dialCode: "+1721",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "SK",
    label: "Slovakia",
    currency: "EUR",
    timezone: "Europe/Bratislava",
    dialCode: "+421",
    defaultVatPercent: 20,
    localityPlaceholders: [],
  },
  {
    countryCode: "SI",
    label: "Slovenia",
    currency: "EUR",
    timezone: "Europe/Ljubljana",
    dialCode: "+386",
    defaultVatPercent: 22,
    localityPlaceholders: [],
  },
  {
    countryCode: "SB",
    label: "Solomon Islands",
    currency: "SBD",
    timezone: "Pacific/Guadalcanal",
    dialCode: "+677",
    defaultVatPercent: 10,
    localityPlaceholders: [],
  },
  {
    countryCode: "SO",
    label: "Somalia",
    currency: "SOS",
    timezone: "Africa/Mogadishu",
    dialCode: "+252",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "ZA",
    label: "South Africa",
    currency: "ZAR",
    timezone: "Africa/Johannesburg",
    dialCode: "+27",
    defaultVatPercent: 15,
    localityPlaceholders: ["Johannesburg","Cape Town","Durban","Pretoria","Gqeberha"],
  },
  {
    countryCode: "GS",
    label: "South Georgia and the South Sandwich Islands",
    currency: "GBP",
    timezone: "Atlantic/South_Georgia",
    dialCode: "+500",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "KR",
    label: "South Korea",
    currency: "KRW",
    timezone: "Asia/Seoul",
    dialCode: "+82",
    defaultVatPercent: 10,
    localityPlaceholders: [],
  },
  {
    countryCode: "SS",
    label: "South Sudan",
    currency: "SSP",
    timezone: "Africa/Juba",
    dialCode: "+211",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "ES",
    label: "Spain",
    currency: "EUR",
    timezone: "Europe/Madrid",
    dialCode: "+34",
    defaultVatPercent: 21,
    localityPlaceholders: [],
  },
  {
    countryCode: "LK",
    label: "Sri Lanka",
    currency: "LKR",
    timezone: "Asia/Colombo",
    dialCode: "+94",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "SD",
    label: "Sudan",
    currency: "SDG",
    timezone: "Africa/Khartoum",
    dialCode: "+249",
    defaultVatPercent: 17,
    localityPlaceholders: [],
  },
  {
    countryCode: "SR",
    label: "Suriname",
    currency: "SRD",
    timezone: "America/Paramaribo",
    dialCode: "+597",
    defaultVatPercent: 10,
    localityPlaceholders: [],
  },
  {
    countryCode: "SJ",
    label: "Svalbard and Jan Mayen",
    currency: "NOK",
    timezone: "Arctic/Longyearbyen",
    dialCode: "+47",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "SE",
    label: "Sweden",
    currency: "SEK",
    timezone: "Europe/Stockholm",
    dialCode: "+46",
    defaultVatPercent: 25,
    localityPlaceholders: [],
  },
  {
    countryCode: "CH",
    label: "Switzerland",
    currency: "CHF",
    timezone: "Europe/Zurich",
    dialCode: "+41",
    defaultVatPercent: 8.1,
    localityPlaceholders: [],
  },
  {
    countryCode: "SY",
    label: "Syria",
    currency: "SYP",
    timezone: "Asia/Damascus",
    dialCode: "+963",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "TW",
    label: "Taiwan",
    currency: "TWD",
    timezone: "Asia/Taipei",
    dialCode: "+886",
    defaultVatPercent: 5,
    localityPlaceholders: [],
  },
  {
    countryCode: "TJ",
    label: "Tajikistan",
    currency: "TJS",
    timezone: "Asia/Dushanbe",
    dialCode: "+992",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "TZ",
    label: "Tanzania",
    currency: "TZS",
    timezone: "Africa/Dar_es_Salaam",
    dialCode: "+255",
    defaultVatPercent: 18,
    localityPlaceholders: ["Dar es Salaam","Arusha","Mwanza","Dodoma","Zanzibar"],
  },
  {
    countryCode: "TH",
    label: "Thailand",
    currency: "THB",
    timezone: "Asia/Bangkok",
    dialCode: "+66",
    defaultVatPercent: 7,
    localityPlaceholders: [],
  },
  {
    countryCode: "TL",
    label: "Timor-Leste",
    currency: "USD",
    timezone: "Asia/Dili",
    dialCode: "+670",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "TG",
    label: "Togo",
    currency: "XOF",
    timezone: "Africa/Lome",
    dialCode: "+228",
    defaultVatPercent: 18,
    localityPlaceholders: [],
  },
  {
    countryCode: "TK",
    label: "Tokelau",
    currency: "NZD",
    timezone: "Pacific/Fakaofo",
    dialCode: "+690",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "TO",
    label: "Tonga",
    currency: "TOP",
    timezone: "Pacific/Tongatapu",
    dialCode: "+676",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "TT",
    label: "Trinidad and Tobago",
    currency: "TTD",
    timezone: "America/Port_of_Spain",
    dialCode: "+1868",
    defaultVatPercent: 12.5,
    localityPlaceholders: [],
  },
  {
    countryCode: "TN",
    label: "Tunisia",
    currency: "TND",
    timezone: "Africa/Tunis",
    dialCode: "+216",
    defaultVatPercent: 19,
    localityPlaceholders: [],
  },
  {
    countryCode: "TR",
    label: "Türkiye",
    currency: "TRY",
    timezone: "Europe/Istanbul",
    dialCode: "+90",
    defaultVatPercent: 20,
    localityPlaceholders: [],
  },
  {
    countryCode: "TM",
    label: "Turkmenistan",
    currency: "TMT",
    timezone: "Asia/Ashgabat",
    dialCode: "+993",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "TC",
    label: "Turks and Caicos Islands",
    currency: "USD",
    timezone: "America/Grand_Turk",
    dialCode: "+1649",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "TV",
    label: "Tuvalu",
    currency: "AUD",
    timezone: "Pacific/Funafuti",
    dialCode: "+688",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "UM",
    label: "U.S. Minor Outlying Islands",
    currency: "USD",
    timezone: "Pacific/Wake",
    dialCode: "+1",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "VI",
    label: "U.S. Virgin Islands",
    currency: "USD",
    timezone: "America/St_Thomas",
    dialCode: "+1340",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "UG",
    label: "Uganda",
    currency: "UGX",
    timezone: "Africa/Kampala",
    dialCode: "+256",
    defaultVatPercent: 18,
    localityPlaceholders: ["Kampala","Entebbe","Jinja","Gulu","Mbarara"],
  },
  {
    countryCode: "UA",
    label: "Ukraine",
    currency: "UAH",
    timezone: "Europe/Kyiv",
    dialCode: "+380",
    defaultVatPercent: 20,
    localityPlaceholders: [],
  },
  {
    countryCode: "AE",
    label: "United Arab Emirates",
    currency: "AED",
    timezone: "Asia/Dubai",
    dialCode: "+971",
    defaultVatPercent: 5,
    localityPlaceholders: ["Dubai","Abu Dhabi","Sharjah","Ajman","Al Ain"],
  },
  {
    countryCode: "GB",
    label: "United Kingdom",
    currency: "GBP",
    timezone: "Europe/London",
    dialCode: "+44",
    defaultVatPercent: 20,
    localityPlaceholders: ["London","Manchester","Birmingham","Leeds","Glasgow"],
  },
  {
    countryCode: "US",
    label: "United States",
    currency: "USD",
    timezone: "America/New_York",
    dialCode: "+1",
    defaultVatPercent: 0,
    localityPlaceholders: ["New York","Los Angeles","Chicago","Houston","Miami"],
  },
  {
    countryCode: "UY",
    label: "Uruguay",
    currency: "UYU",
    timezone: "America/Montevideo",
    dialCode: "+598",
    defaultVatPercent: 22,
    localityPlaceholders: [],
  },
  {
    countryCode: "UZ",
    label: "Uzbekistan",
    currency: "UZS",
    timezone: "Asia/Tashkent",
    dialCode: "+998",
    defaultVatPercent: 12,
    localityPlaceholders: [],
  },
  {
    countryCode: "VU",
    label: "Vanuatu",
    currency: "VUV",
    timezone: "Pacific/Efate",
    dialCode: "+678",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  },
  {
    countryCode: "VA",
    label: "Vatican City",
    currency: "EUR",
    timezone: "Europe/Vatican",
    dialCode: "+379",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "VE",
    label: "Venezuela",
    currency: "VES",
    timezone: "America/Caracas",
    dialCode: "+58",
    defaultVatPercent: 16,
    localityPlaceholders: [],
  },
  {
    countryCode: "VN",
    label: "Vietnam",
    currency: "VND",
    timezone: "Asia/Ho_Chi_Minh",
    dialCode: "+84",
    defaultVatPercent: 10,
    localityPlaceholders: [],
  },
  {
    countryCode: "WF",
    label: "Wallis and Futuna",
    currency: "XPF",
    timezone: "Pacific/Wallis",
    dialCode: "+681",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "EH",
    label: "Western Sahara",
    currency: "MAD",
    timezone: "Africa/El_Aaiun",
    dialCode: "+212",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "YE",
    label: "Yemen",
    currency: "YER",
    timezone: "Asia/Aden",
    dialCode: "+967",
    defaultVatPercent: 0,
    localityPlaceholders: [],
  },
  {
    countryCode: "ZM",
    label: "Zambia",
    currency: "ZMW",
    timezone: "Africa/Lusaka",
    dialCode: "+260",
    defaultVatPercent: 16,
    localityPlaceholders: [],
  },
  {
    countryCode: "ZW",
    label: "Zimbabwe",
    currency: "ZWG",
    timezone: "Africa/Harare",
    dialCode: "+263",
    defaultVatPercent: 15,
    localityPlaceholders: [],
  }
] as const;

export const WORLD_COUNTRY_DEFAULTS: Record<
  string,
  { currency: string; timezone: string }
> = Object.fromEntries(
  WORLD_REGION_DEFAULTS.map((r) => [
    r.countryCode,
    { currency: r.currency, timezone: r.timezone },
  ]),
);

export function findWorldRegion(countryCode: string): WorldRegionDefault | undefined {
  const code = countryCode.trim().toUpperCase();
  return WORLD_REGION_DEFAULTS.find((r) => r.countryCode === code);
}
