# Install Palmart Till Print Bridge on Windows 7 (no Node.js).
# ASCII-only. Works with Windows PowerShell 2.0+.
$ErrorActionPreference = "Stop"

$PkgDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$InstallDir = Join-Path $env:LOCALAPPDATA "Palmart\till-print-bridge"
$BridgeSrc = Join-Path $PkgDir "till-print-bridge-win7.ps1"
$BridgeDst = Join-Path $InstallDir "till-print-bridge-win7.ps1"
$VbsPath = Join-Path $InstallDir "run-hidden.vbs"
$LogPath = Join-Path $InstallDir "bridge.log"
$StartCmdPath = Join-Path $InstallDir "start-till-print-bridge.cmd"
$TaskName = "PalmartTillPrintBridge"
$StartupName = "Palmart-Till-Print-Bridge.vbs"
$HealthUrl = "http://127.0.0.1:19500/health"
$Port = 19500

function Write-Step([string]$Message) {
  Write-Host (" - " + $Message)
}

function Test-BridgeHealth {
  try {
    $wc = New-Object System.Net.WebClient
    $text = $wc.DownloadString($HealthUrl)
    if ($text -match '"ok"\s*:\s*true') { return $true }
    return $false
  } catch {
    return $false
  }
}

function Wait-BridgeHealth([int]$Attempts = 20) {
  for ($i = 0; $i -lt $Attempts; $i++) {
    if (Test-BridgeHealth) { return $true }
    Start-Sleep -Milliseconds 700
  }
  return $false
}

function Write-HiddenVbs([string]$PowerShellExe, [string]$BridgeFile, [string]$WorkDir, [string]$OutVbs, [string]$OutLog) {
  $psEsc = $PowerShellExe.Replace('"', '""')
  $bridgeEsc = $BridgeFile.Replace('"', '""')
  $workEsc = $WorkDir.Replace('"', '""')
  $logEsc = $OutLog.Replace('"', '""')
  $lines = @(
    "' Auto-generated by Palmart Win7 installer - do not edit.",
    'Set sh = CreateObject("WScript.Shell")',
    ('sh.CurrentDirectory = "' + $workEsc + '"'),
    ('sh.Environment("Process")("TILL_PRINT_BRIDGE_LOG") = "' + $logEsc + '"'),
    "' 0 = hidden, False = do not wait",
    ('sh.Run """' + $psEsc + '"" -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File """' + $bridgeEsc + '""", 0, False')
  )
  [System.IO.File]::WriteAllLines($OutVbs, $lines, [System.Text.Encoding]::ASCII)
}

function Install-StartupEntry([string]$SourceVbs) {
  $startupDir = [Environment]::GetFolderPath("Startup")
  if (-not $startupDir) { return $null }
  if (-not (Test-Path $startupDir)) {
    New-Item -ItemType Directory -Force -Path $startupDir | Out-Null
  }
  $dest = Join-Path $startupDir $StartupName
  Copy-Item -Force $SourceVbs $dest
  return $dest
}

function Install-LogonTaskSchtasks([string]$VbsFile) {
  # Windows 7 schtasks: pass ONLY the .vbs path as /TR (shell opens it with wscript).
  # Do NOT put wscript.exe + quoted path in /TR - Start-Process splits it and
  # schtasks treats the .vbs path as an invalid extra switch.
  if (-not (Test-Path $VbsFile)) {
    throw ("Missing launcher: " + $VbsFile)
  }

  # Ignore delete failure when the task does not exist yet.
  Start-Process -FilePath "schtasks.exe" -ArgumentList @("/Delete", "/TN", $TaskName, "/F") -Wait -NoNewWindow -ErrorAction SilentlyContinue | Out-Null

  $p = Start-Process -FilePath "schtasks.exe" -ArgumentList @(
    "/Create",
    "/TN", $TaskName,
    "/TR", $VbsFile,
    "/SC", "ONLOGON",
    "/F"
  ) -Wait -PassThru -NoNewWindow
  if ($null -eq $p -or $p.ExitCode -ne 0) {
    $code = 1
    if ($p) { $code = $p.ExitCode }
    throw ("schtasks create failed with exit " + $code)
  }

  Start-Process -FilePath "schtasks.exe" -ArgumentList @("/Run", "/TN", $TaskName) -Wait -NoNewWindow -ErrorAction SilentlyContinue | Out-Null
}

if (-not (Test-Path $BridgeSrc)) {
  throw "Missing till-print-bridge-win7.ps1 next to this installer."
}

$psExe = Join-Path $env:SystemRoot "System32\WindowsPowerShell\v1.0\powershell.exe"
if (-not (Test-Path $psExe)) {
  $psExe = "powershell.exe"
}
$Wscript = Join-Path $env:SystemRoot "System32\wscript.exe"
if (-not (Test-Path $Wscript)) {
  $Wscript = "wscript.exe"
}

Write-Host ""
Write-Host "=== Palmart Till Print Bridge - Windows 7 install ==="
Write-Step ("PowerShell: " + $psExe)
Write-Step ("Install dir: " + $InstallDir)
Write-Step "No Node.js required on Windows 7."

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
Copy-Item -Force $BridgeSrc $BridgeDst
Write-HiddenVbs -PowerShellExe $psExe -BridgeFile $BridgeDst -WorkDir $InstallDir -OutVbs $VbsPath -OutLog $LogPath

[System.IO.File]::WriteAllLines($StartCmdPath, @(
  "@echo off",
  'cd /d "%~dp0"',
  'start "" /B wscript.exe "%~dp0run-hidden.vbs"',
  "echo Started Till Print Bridge in the background.",
  "ping -n 3 127.0.0.1 >nul"
), [System.Text.Encoding]::ASCII)

$startupPath = $null
try {
  $startupPath = Install-StartupEntry -SourceVbs $VbsPath
  if ($startupPath) { Write-Step ("Startup folder: " + $startupPath) }
} catch {
  Write-Warning ("Could not add Startup folder entry: " + $_.Exception.Message)
}

$taskOk = $false
try {
  Install-LogonTaskSchtasks -VbsFile $VbsPath
  $taskOk = $true
  Write-Step ("Scheduled task: " + $TaskName + " (schtasks ONLOGON)")
} catch {
  # Startup folder entry is enough for daily use on Windows 7.
  Write-Warning ("Scheduled task skipped (Startup folder still used): " + $_.Exception.Message)
}

if (Test-BridgeHealth) {
  Write-Step ("Bridge already healthy on port " + $Port)
} else {
  Start-Process -FilePath $Wscript -ArgumentList ('"' + $VbsPath + '"') -WindowStyle Hidden | Out-Null
  Write-Step "Started bridge in background (no window)"
}

$ok = Wait-BridgeHealth
Write-Host ""
if ($ok) {
  Write-Host "OK - Windows 7 bridge installed and running at http://127.0.0.1:19500"
  Write-Host "It starts automatically when you sign in. No window to leave open. No Node.js."
  if ($taskOk) {
    Write-Host ("Autostart: Startup folder + schtasks (" + $TaskName + ")")
  } else {
    Write-Host "Autostart: Startup folder"
  }
  Write-Host ("Logs: " + $LogPath)
  Write-Host ""
  Write-Host "Go back to Palmart Cashier and click Detect printers."
  Write-Host "Tip: use Chrome 109 (last Chrome for Windows 7) for the cashier site."
} else {
  Write-Warning "Files installed, but health check failed."
  Write-Warning ("Log file: " + $LogPath)
  Write-Warning ("Try: " + $StartCmdPath)
  Write-Warning "If URL reservation fails, run once as Administrator, or:"
  Write-Warning ("  netsh http add urlacl url=http://127.0.0.1:19500/ user=" + $env:USERNAME)
  throw "Bridge did not become healthy on http://127.0.0.1:19500"
}
