# Install Palmart Till Print Bridge on Windows 7 (no Node.js).
# ASCII-only. Works with Windows PowerShell 2.0+.
# Autostart = Startup folder only (schtasks is unreliable on Win7).
$ErrorActionPreference = "Stop"

$PkgDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$InstallDir = Join-Path $env:LOCALAPPDATA "Palmart\till-print-bridge"
$BridgeSrc = Join-Path $PkgDir "till-print-bridge-win7.ps1"
$BridgeDst = Join-Path $InstallDir "till-print-bridge-win7.ps1"
$VbsPath = Join-Path $InstallDir "run-hidden.vbs"
$LogPath = Join-Path $InstallDir "bridge.log"
$StartCmdPath = Join-Path $InstallDir "start-till-print-bridge.cmd"
$StartupName = "Palmart-Till-Print-Bridge.vbs"
$HealthUrl = "http://127.0.0.1:19500/health"
$Port = 19500

function Write-Step([string]$Message) {
  Write-Host (" - " + $Message)
}

function Test-BridgeHealth {
  try {
    $wc = New-Object System.Net.WebClient
    $text = $wc.DownloadString($HealthUrl)
    if ($text -match '"ok"\s*:\s*true') { return $true }
    return $false
  } catch {
    return $false
  }
}

function Wait-BridgeHealth([int]$Attempts = 25) {
  for ($i = 0; $i -lt $Attempts; $i++) {
    if (Test-BridgeHealth) { return $true }
    Start-Sleep -Milliseconds 800
  }
  return $false
}

function Write-HiddenVbs([string]$PowerShellExe, [string]$BridgeFile, [string]$WorkDir, [string]$OutVbs, [string]$OutLog) {
  # Use Chr(34) for quotes - nested """ quoting breaks VBScript on Windows 7
  # (Error 800A0401 Expected end of statement).
  $psLit = $PowerShellExe.Replace('"', '')
  $bridgeLit = $BridgeFile.Replace('"', '')
  $workLit = $WorkDir.Replace('"', '')
  $logLit = $OutLog.Replace('"', '')
  $lines = @(
    "' Auto-generated by Palmart Win7 installer - do not edit.",
    'Set sh = CreateObject("WScript.Shell")',
    ('sh.CurrentDirectory = "' + $workLit + '"'),
    ('sh.Environment("Process")("TILL_PRINT_BRIDGE_LOG") = "' + $logLit + '"'),
    ('ps = "' + $psLit + '"'),
    ('bridge = "' + $bridgeLit + '"'),
    'cmd = Chr(34) & ps & Chr(34) & " -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File " & Chr(34) & bridge & Chr(34)',
    "' 0 = hidden window, False = do not wait",
    "sh.Run cmd, 0, False"
  )
  [System.IO.File]::WriteAllLines($OutVbs, $lines, [System.Text.Encoding]::ASCII)
}

function Install-StartupEntry([string]$SourceVbs) {
  $startupDir = [Environment]::GetFolderPath("Startup")
  if (-not $startupDir) { return $null }
  if (-not (Test-Path $startupDir)) {
    New-Item -ItemType Directory -Force -Path $startupDir | Out-Null
  }
  $dest = Join-Path $startupDir $StartupName
  Copy-Item -Force $SourceVbs $dest
  return $dest
}

function Start-BridgeHidden([string]$WscriptExe, [string]$VbsFile) {
  # Prefer shell execute so .vbs associates correctly on Windows 7.
  $psi = New-Object System.Diagnostics.ProcessStartInfo
  $psi.FileName = $WscriptExe
  $psi.Arguments = '"' + $VbsFile + '"'
  $psi.WorkingDirectory = (Split-Path -Parent $VbsFile)
  $psi.WindowStyle = [System.Diagnostics.ProcessWindowStyle]::Hidden
  $psi.UseShellExecute = $true
  [void][System.Diagnostics.Process]::Start($psi)
}

if (-not (Test-Path $BridgeSrc)) {
  throw "Missing till-print-bridge-win7.ps1 next to this installer."
}

$psExe = Join-Path $env:SystemRoot "System32\WindowsPowerShell\v1.0\powershell.exe"
if (-not (Test-Path $psExe)) {
  $psExe = "powershell.exe"
}
$Wscript = Join-Path $env:SystemRoot "System32\wscript.exe"
if (-not (Test-Path $Wscript)) {
  $Wscript = "wscript.exe"
}

Write-Host ""
Write-Host "=== Palmart Till Print Bridge - Windows 7 install ==="
Write-Step ("PowerShell: " + $psExe)
Write-Step ("Install dir: " + $InstallDir)
Write-Step "No Node.js required on Windows 7."

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
Copy-Item -Force $BridgeSrc $BridgeDst
Write-HiddenVbs -PowerShellExe $psExe -BridgeFile $BridgeDst -WorkDir $InstallDir -OutVbs $VbsPath -OutLog $LogPath
if (-not (Test-Path $VbsPath)) {
  throw ("Failed to write launcher: " + $VbsPath)
}
Write-Step ("Launcher: " + $VbsPath)

[System.IO.File]::WriteAllLines($StartCmdPath, @(
  "@echo off",
  'cd /d "%~dp0"',
  'start "" /B wscript.exe "%~dp0run-hidden.vbs"',
  "echo Started Till Print Bridge in the background.",
  "ping -n 3 127.0.0.1 >nul"
), [System.Text.Encoding]::ASCII)

$startupPath = $null
try {
  $startupPath = Install-StartupEntry -SourceVbs $VbsPath
  if ($startupPath) {
    Write-Step ("Startup folder: " + $startupPath)
  } else {
    Write-Warning "Could not resolve Startup folder."
  }
} catch {
  Write-Warning ("Could not add Startup folder entry: " + $_.Exception.Message)
}

# Do not use schtasks on Windows 7 - quoting/API differences cause false errors.
# Startup folder is the supported autostart method.
Write-Step "Autostart: Startup folder (no Task Scheduler on Windows 7)"

if (Test-BridgeHealth) {
  Write-Step ("Bridge already healthy on port " + $Port)
} else {
  Start-BridgeHidden -WscriptExe $Wscript -VbsFile $VbsPath
  Write-Step "Started bridge in background (no window)"
}

$ok = Wait-BridgeHealth
Write-Host ""
if ($ok) {
  Write-Host "OK - Windows 7 bridge installed and running at http://127.0.0.1:19500"
  Write-Host "It starts automatically when you sign in to Windows."
  Write-Host "No window to leave open. No Node.js. No Task Scheduler needed."
  if ($startupPath) {
    Write-Host ("Autostart file: " + $startupPath)
  }
  Write-Host ("Logs: " + $LogPath)
  Write-Host ""
  Write-Host "Go back to Palmart Cashier and click Detect printers."
  Write-Host "Tip: use Chrome 109 (last Chrome for Windows 7) for the cashier site."
  exit 0
}

Write-Warning "Files installed, but health check failed."
Write-Warning ("Log file: " + $LogPath)
Write-Warning ("Try double-click: " + $StartCmdPath)
Write-Warning "Or open this in Internet Explorer on this PC:"
Write-Warning "  http://127.0.0.1:19500/health"
Write-Warning "You should see ok:true. If the page will not load, check bridge.log."
throw "Bridge did not become healthy on http://127.0.0.1:19500"
